# -*- coding: UTF-8 -*-
# generated by lino.sphinxcontrib.help_text_builder
from __future__ import unicode_literals
from django.utils.translation import ugettext_lazy as _

help_texts = {
    'lino_tera.lib.tera.migrate.Migrator' : _("""The standard migrator for tera."""),
    'lino_tera.lib.tera.migrate.Migrator.migrate_from_18_8_0' : _("""min_asset and number_of_events now in Tarif instead Product"""),
    'lino_tera.lib.cal.Event.amount' : _("""The amount perceived during this appointment."""),
}
